-- Oracle XE: CDS용 스키마(C##cds) 생성
-- SYS 등 관리자 계정으로 XEPDB1에 접속한 뒤 실행하세요.

ALTER SESSION SET CONTAINER = XEPDB1;

DROP USER C##cds CASCADE;

CREATE USER C##cds IDENTIFIED BY 1234
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CONNECT, RESOURCE TO C##cds;

COMMIT;
